services:
  psql:
    # build: .
    image: postgres:17.0
    container_name: formula_bi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql123
      POSTGRES_DB: formula_bi
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - fbi-data:/var/lib/postgresql/data/pgdata
      - ./dump_fbi.sql:/docker-entrypoint-initdb.d/dump_fbi_17_11_24.sql
    restart: unless-stopped
volumes:
  fbi-data: