version: '3.9'
services:
  psql:
    build: .
    container_name: formula_bi_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: psql123
      POSTGRES_DB: formula_bi
    command: bash -c "chmod +x /init-db.sh && /init-db.sh"
    ports:
      - "5432:5432"
    restart: unless-stopped



